from ows_refactored.ows_reslim_cfg import reslim_standard

bands_burncube = {
    "style_burncube": [],
}

pq_ba = [
    {
        "band": "land",
        "invert": True,
        "values": [0],
    }
]

style_burncube = {
    "name": "burncube",
    "title": "Burnt Area",
    # "abstract": "words here",
    # "needed_bands": ["delta_bsi"],
    # "index_function": {
    #     "function": "datacube_ows.band_utils.single_band",
    #     "mapped_bands": True,
    #     "kwargs": {
    #         "band": "delta_bsi",
    #     },
    # },
    "pq_masks": pq_ba,
    "value_map": {
        "Burnt area": [
            {
                "title": "Burncube",
                "abstract": "Burnt area",
                "color": "#833d08",
            },
        ]
    },
    "legend": {},
}

# layer = {
#     "title": "DEA Burncube Burnt Area",
#     "abstract": "",
#     "layers": [
#         {
#             "title": "DEA Mangroves (Landsat)",
#             "name": "ga_ls_mangrove_cover_cyear_3",
#             "abstract": """Mangrove Canopy Cover 30m 3.0.0 (Landsat, Collection 3)

# Mangrove canopy cover version 3.0.0, 30 metre. Data is only visible at higher resolutions; when zoomed-out the available area will be displayed as a shaded region.
# The mangrove canopy cover product provides valuable information about the extent and canopy density of mangroves for each year between 1987 and 2021 for the entire Australian coastline.
# The canopy cover classes are:
# 20-50% (pale green), 50-80% (mid green), 80-100% (dark green).
# The product consists of  a sequence (one per year) of 30 meter resolution maps that are generated by analysing the Landsat fractional cover (https://doi.org/10.6084/m9.figshare.94250.v1) developed by the Joint Remote Sensing Research Program and the Global Mangrove Watch layers (https://doi.org/10.1071/MF13177) developed by the Japanese Aerospace Exploration Agency.

# https://cmi.ga.gov.au/data-products/dea/634/dea-mangrove-canopy-cover-landsat

# For service status information, see https://status.dea.ga.gov.au""",
#             "product_name": "ga_ls_mangrove_cover_cyear_3",
#             "bands": bands_mangrove,
#             "resource_limits": reslim_standard,
#             "native_crs": "EPSG:3577",
#             "native_resolution": [30, -30],
#             "time_resolution": "year",
#             "image_processing": {
#                 "extent_mask_func": "datacube_ows.ogc_utils.mask_by_val",
#             },
            "styling": {
                "default_style": "burncube",
                "styles": [
                    style_burncube,
                ],
            },
        },
    ],
}
