from ows_refactored.ows_reslim_cfg import reslim_standard

bands_mangrove = {
    "canopy_cover_class": [],
}

style_mangrove_cover_v4 = {
    "name": "mangrove",
    "title": "Mangrove Cover",
    "abstract": "",
    "value_map": {
        "canopy_cover_class": [
            {
                "title": "Not Observed",
                "abstract": "(Clear Obs < 3)",
                "flags": {"notobserved": True},
                "color": "#BDBDBD",
            },
            {
                "title": "Woodland",
                "abstract": "(20% - 50% cover)",
                "flags": {"woodland": True},
                "color": "#9FFF4C",
            },
            {
                "title": "Open Forest",
                "abstract": "(50% - 80% cover)",
                "flags": {"open_forest": True},
                "color": "#5ECC00",
            },
            {
                "title": "Closed Forest",
                "abstract": "(>80% cover)",
                "flags": {"closed_forest": True},
                "color": "#3B7F00",
            },
        ]
    },
    "legend": {},
}

layer = {
    "title": "DEA Mangroves",
    "abstract": "",
    "layers": [
        {
            "title": "DEA Mangroves (Landsat)",
            "name": "ga_ls_mangrove_cover_cyear_3",
            "abstract": """Mangrove Canopy Cover 30m (Landsat, Collection 3)

Mangrove canopy cover, 30 metre. Data is only visible at higher resolutions; when zoomed-out the available area will be displayed as a shaded region.
The mangrove canopy cover product provides valuable information about the extent and canopy density of mangroves for each full year between 1987 and the present for the entire Australian coastline.
The canopy cover classes are:
20-50% (pale green), 50-80% (mid green), 80-100% (dark green).
The product consists of  a sequence (one per year) of 30 meter resolution maps that are generated by analysing the Landsat fractional cover (https://doi.org/10.6084/m9.figshare.94250.v1) developed by the Joint Remote Sensing Research Program and the Global Mangrove Watch layers (https://doi.org/10.1071/MF13177) developed by the Japanese Aerospace Exploration Agency.

https://knowledge.dea.ga.gov.au/data/product/dea-mangrove-canopy-cover-landsat/

For service status information, see https://status.dea.ga.gov.au""",
            "product_name": "ga_ls_mangrove_cover_cyear_3",
            "bands": bands_mangrove,
            "resource_limits": reslim_standard,
            "native_crs": "EPSG:3577",
            "native_resolution": [30, -30],
            "time_resolution": "summary",
            "image_processing": {
                "extent_mask_func": "datacube_ows.ogc_utils.mask_by_val",
            },
            "styling": {
                "default_style": "mangrove",
                "styles": [
                    style_mangrove_cover_v4,
                ],
            },
        },
    ],
}
