codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 80%
  precision: 2
  round: down
  range: "20...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

fixes:
  - /dea-config::

# sample regex patterns
ignore:
  - "/dea-config/coverage_test"  # ignore folders and all its contents
  - "/dea-config/**/*.yaml"         # glob accepted
  - "/dea-config/**/*.csv"         # glob accepted
  - "/dea-config/**/*.json"         # glob accepted
  - "/dea-config/**/*.cfg"         # glob accepted

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no