pull_request_rules:
  - name: automatic merge when CI passes and reviewed
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Docker Image CI
      - base=master
    actions:
      merge:
        method: merge
  - name: delete merged branches
    conditions:
      - merged
    actions:
      delete_head_branch:
