
version: '3.4'

# Default compose will create an ows image, with dev settings and connect to a local db
services:
  odc:
    image: opendatacube/datacube-index:latest
    environment:
      # # Defaults are defined in .env file
      DB_HOSTNAME: postgres
      DB_USERNAME: opendatacube
      DB_PASSWORD: opendatacubepassword
      DB_DATABASE: opendatacube
      DB_PORT: 5432
      AWS_DEFAULT_REGION: ap-southeast-2
      PYTHONPATH: /env/config
    depends_on:
      - postgres
    volumes:
      - ./product-def-validator.sh:/env/config/product-def-validator.sh
      - ${PRODUCT_DEF_FILE}:/env/config/products.csv
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]

  postgres:
    build: docker/database/
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - "5432:5432"
    restart: always
