
version: '3.4'

# Default compose will create an ows image, with dev settings and connect to a local db
services:
  product:
    image: opendatacube/datacube-index:latest
    environment:
      # # Defaults are defined in .env file
      DB_HOSTNAME: postgres
      DB_USERNAME: opendatacube
      DB_PASSWORD: opendatacubepassword
      DB_DATABASE: opendatacube
      DB_PORT: 5432
      AWS_DEFAULT_REGION: ap-southeast-2
    depends_on:
      - postgres
    volumes:
      - ./products:/env/config/products
      - ./check-dev-product-csv.sh:/env/config/check-dev-product-csv.sh
      - ./check-prod-product-csv.sh:/env/config/check-prod-product-csv.sh
      - ./workspaces/prod-products.csv:/env/config/prod-products.csv
      - ./workspaces/dev-products.csv:/env/config/dev-products.csv
    command: tail -f /dev/null

  postgres:
    image: kartoza/postgis:13-3.1
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    # ports:
    #   - "5432:5432"
    restart: always
