
version: '3.4'

# Default compose will create an ows image, with dev settings and connect to a local db
services:
  ows:
    image: opendatacube/ows:latest
    environment:
      # # Defaults are defined in .env file
      WMS_CONFIG_PATH: /env/config/ows_refactored/ows_root_cfg.py
      # # Path from the PYTHONPATH to the config object (default PYTHONPATH is /env)
      DATACUBE_OWS_CFG: ows_refactored.ows_root_cfg.ows_cfg
      AWS_DEFAULT_REGION: ap-southeast-2
      PYTHONPATH: /env/config
    volumes:
      - ${OWS_CFG_MOUNT}:/env/config/ows_refactored
    # command:
    #   /bin/sh -c "datacube-ows-cfg-parse -p"