
version: '3.4'

# Default compose will create an ows image, with dev settings and connect to a local db
services:
  ows:
    image: opendatacube/ows:latest
    environment:
      # Defaults are defined in .env file
      DB_HOSTNAME: postgres
      DB_USERNAME: opendatacube
      DB_PASSWORD: opendatacubepassword
      DB_DATABASE: opendatacube
      DB_PORT: 5432
      WMS_CONFIG_PATH: /env/config/ows_refactored/ows_root_cfg.py
      # Path from the PYTHONPATH to the config object (default PYTHONPATH is /env)
      DATACUBE_OWS_CFG: ows_refactored.ows_root_cfg.ows_cfg
      AWS_DEFAULT_REGION: ap-southeast-2
      # Talk to AWS without using credentials
      AWS_NO_SIGN_REQUEST: yes
      # Enable Metrics
      prometheus_multiproc_dir: /tmp
      # Dev flags
      FLASK_APP: /code/datacube_ows/ogc.py
      FLASK_ENV: development
      PYTHONPATH: /env/config
    depends_on:
      - postgres
    environment:
      DB_PORT: 5432
    volumes:
      - ${OWS_CFG_MOUNT}:/env/config/
      - ./:/code/

  postgres:
    # db with some data from ls8_usgs_level1_scene pre-indexed
    image: kartoza/postgis:11.0-2.5
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - "5432:5432"
    restart: always