# Default compose will create an ows image, with dev settings and connect to a local db
services:
  ows:
    image: opendatacube/ows:latest
    environment:
      # # Defaults are defined in .env file
      - ODC_DEFAULT_DB_HOSTNAME=postgres
      - ODC_DEFAULT_DB_USERNAME=opendatacube
      - ODC_DEFAULT_DB_PASSWORD=opendatacubepassword
      - ODC_DEFAULT_DB_DATABASE=opendatacube
      - WMS_CONFIG_PATH=/dea-config/${OWS_CFG_PATH}
      # # Path from the PYTHONPATH to the config object (default PYTHONPATH is /env)
      - DATACUBE_OWS_CFG=${DATACUBE_OWS_CFG}
      - AWS_DEFAULT_REGION=ap-southeast-2
      - PYTHONPATH=/dea-config/${PYTHON_PATH}
      - INVENTORY=/dea-config/${PYTHON_PATH}/inventory.json
    depends_on:
      postgres:
        condition: service_healthy
    command: tail -f /dev/null
    volumes:
      - ./:/dea-config/
      - ./artifacts:/mnt/artifacts

  postgres:
    image: kartoza/postgis:13-3.1
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
