
version: '3.4'

# Default compose will create an ows image, with dev settings and connect to a local db
services:
  datacube:
    image: opendatacube/datacube-index:latest
    environment:
      # # Defaults are defined in .env file
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - AWS_DEFAULT_REGION=ap-southeast-2
      - ENV=${ENV}
      - EXPLORER_ENDPOINT=${EXPLORER_ENDPOINT}
    depends_on:
      - postgres
    volumes:
      - ./products:/env/config/products
      - ./product_metadata:/env/config/product_metadata
      - ./datacube_init_metadata.sh:/env/config/datacube_init_metadata.sh
      - ./check-product-definitions.sh:/env/config/check-product-definitions.sh
      - ./check-product-csv.sh:/env/config/check-product-csv.sh
      - ./local-check-script.sh:/env/config/local-check-script.sh
      - ./workspaces/prod-products.csv:/env/config/prod-products.csv
      - ./workspaces/dev-products.csv:/env/config/dev-products.csv
    command: tail -f /dev/null

  postgres:
    image: postgres:12.6-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: opendatacubepassword
    restart: always
