name: ls8_barest_earth_albers
description: Landsat-8 Barest Earth pixel composite albers 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)
metadata_type: eo
metadata:
  product_type: landsat8_barest_earth_mosaic
  platform:
    code: LANDSAT_8
  format:
    name: GeoTIFF
  instrument:
    name: OLI
storage:
  driver: GeoTIFF
  crs: EPSG:3577
  tile_size:
    x: 100000.0
    y: 100000.0
  resolution:
    x: 25
    y: -25
  dimension_order: [time, y, x]
# possibly fix the dtype
measurements:
  - name: blue
    dtype: int16
    nodata: -999
    units: '1'
  - name: green
    dtype: int16
    nodata: -999
    units: '1'
  - name: red
    dtype: int16
    nodata: -999
    units: '1'
  - name: nir
    dtype: int16
    nodata: -999
    units: '1'
  - name: swir1
    dtype: int16
    nodata: -999
    units: '1'
  - name: swir2
    dtype: int16
    nodata: -999
    units: '1'

