name : Terria Config

on:
  push:
    paths:
      - 'dev/terria/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'dev/terria/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Run Json Linter
      run: |
        npm install jsonlint -g
        sudo chown -R $(whoami) ~/.npm
        jsonlint dev/terria/dea-maps.json