name : Terria Config

on:
  push:
    paths:
      - 'dev/terria/**'
      - .github/workflows/main.yml
  pull_request:
    branches: [ master ]
    paths:
      - 'dev/terria/**'
      - .github/workflows/main.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Run Json Linter
      run: |
        sudo npm install jsonlint -g
        jsonlint dev/terria/dea-maps.json -q
        jsonlint dev/terria/dea.json -q

    - name: Run Python Linter
      run: |
        python -m pip install pylint boto3
        ./check-code.sh
