name: PRODUCT DEFINITION Test

on:
  push:
    branches: [ master ]
    paths:
      - 'products/**'
      - '.github/workflows/odc_product_testing.yaml'
      - 'docker-compose.productscsv.yaml'
      - 'check-product-definitions.sh'

  pull_request:
    branches: [ master ]
    paths:
      - 'products/**'
      - '.github/workflows/odc_product_testing.yaml'
      - 'docker-compose.productscsv.yaml'
      - 'check-product-definitions.sh'

jobs:
  odc-indexing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run product definition testing
      run: |
        docker-compose -f docker-compose.productscsv.yaml up -d
        docker-compose -f docker-compose.productscsv.yaml exec -T datacube /bin/sh -c "datacube system init"
        docker-compose -f docker-compose.productscsv.yaml exec -T datacube /bin/sh -c "cd /env/config; ./datacube_init_metadata.sh"
        docker-compose -f docker-compose.productscsv.yaml exec -T datacube /bin/sh -c "cd /env/config; ./check-product-definitions.sh"
        docker-compose -f docker-compose.productscsv.yaml down

  eo3-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run eo3-validate for product
      run: |
        docker run -v $PWD/:/code/dea-config opendatacube/eo-datasets:latest eo3-validate \
          ./dea-config/product_metadata \
          ./dea-config/products/baseline_satellite_data \
          ./dea-config/products/hazards \
          ./dea-config/products/inland_water \
          ./dea-config/products/land_and_vegetation \
          ./dea-config/products/sea_ocean_coast
