name: PRODUCT DEFINITION Test

on:
  push:
    paths:
      - 'products/**'
      - 'workspaces/prod-products.csv'
      - '.github/workflows/odc_product_testing.yaml'
      - 'docker-compose.productscsv.yaml'
      - 'check-dev-product-csv.sh'
      - 'check-prod-product-csv.sh'

  pull_request:
    branches: [ master ]
    paths:
      - 'products/**'
      - 'workspaces/prod-products.csv'
      - '.github/workflows/odc_product_testing.yaml'
      - 'docker-compose.productscsv.yaml'
      - 'check-dev-product-csv.sh'
      - 'check-prod-product-csv.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Run csv testing (Dev)
      run: |
        docker-compose -f docker-compose.productscsv.yaml up -d
        docker-compose -f docker-compose.productscsv.yaml exec -T product /bin/sh -c "datacube system init"
        docker-compose -f docker-compose.productscsv.yaml exec -T product /bin/sh -c "cd /env/config; ./check-dev-product-csv.sh"
        docker-compose -f docker-compose.productscsv.yaml down

    - name: Run csv testing (Prod)
      run: |
        docker-compose -f docker-compose.productscsv.yaml up -d
        docker-compose -f docker-compose.productscsv.yaml exec -T product /bin/sh -c "datacube system init"
        docker-compose -f docker-compose.productscsv.yaml exec -T product /bin/sh -c "cd /env/config; ./check-prod-product-csv.sh"
        docker-compose -f docker-compose.productscsv.yaml down