name: OWS PROD CFG Test

on:
  push:
    branches: [ master ]
    paths:
      - 'prod/services/wms/**'
      - .github/workflows/ows_cfg_testing_prod.yaml
      - 'docker/database/**'
      - 'docker-compose.ows.yaml'

  pull_request:
    branches: [ master ]
    paths:
      - 'prod/services/wms/**'
      - .github/workflows/ows_cfg_testing_prod.yaml
      - 'docker/database/**'
      - 'docker-compose.ows.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Run ows_refactored_cfg test (Prod)
      run: |
        docker-compose -f docker-compose.ows.yaml up -d
        docker-compose -f docker-compose.ows.yaml exec -T ows /bin/sh -c "datacube system init"
        docker-compose -f docker-compose.ows.yaml exec -T ows /bin/sh -c "cd /env/config; ./compare-cfg.sh"
        docker-compose -f docker-compose.ows.yaml down
      env:
        OWS_CFG_PATH: prod/services/wms/ows_refactored
        PYTHON_PATH: prod/services/wms/
        DATACUBE_OWS_CFG: ows_refactored.ows_root_cfg.ows_cfg
