name : Terria catalog Linting

on:
  push:
    branches: [ master ]
    paths:
      - 'dev/terria/**'
      - 'prod/terria/**'
      - .github/workflows/terria_linting.yaml
  pull_request:
    branches: [ master ]
    paths:
      - 'dev/terria/**'
      - 'prod/terria/**'
      - .github/workflows/terria_linting.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4

    - name: Run tab detector for Terria Cube
      run: |
        if grep -Pn "\t" dev/terria/*.json; then
            echo 'Please replace tab with white spaces as per the lines indicated'
            exit 1
        fi

    - name: Run Json Linter for Terria Cube
      run: |
        npm install jsonlint -g
        cd dev/terria
        find . -name \*.json -exec jsonlint {} \;

    - name: Run tab detector for DEA Maps
      run: |
        if grep -Pn "\t" prod/terria/*.json; then
            echo 'Please replace tab with white spaces as per the lines indicated'
            exit 1
        fi

    - name: Run Json Linter for DEA Maps
      run: |
        npm install jsonlint -g
        cd prod/terria
        find . -name \*.json -exec jsonlint {} \;
