name: Terria catalog preview

on:
  push:
    branches:
      - terria_config_link
    paths:
      - '.github/workflows/terria_preview.yaml'
      - 'dev/terria/terria-cube-v8.json'
      - 'dev/terria/dea-maps-v8.json'

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:

      - name: Set ticket number
        id: parse-ticket-number
        run: |
            TICKET_NUMBER=$(echo $GITHUB_REF_NAME_SLUG | cut -c1-9 | tr '[:upper:]' '[:lower:]')
            echo "::set-output name= TICKET_NUMBER::$TICKET_NUMBER"

      - uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            **Terria Cube config preview:** https://terria-cube.terria.io/#clean&https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/terria_config_link/dev/terria/terria-cube-v8.json
            
            **DEA Maps config preview:** https://maps.dea.ga.gov.au/#clean&https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/terria_config_link/dev/terria/dea-maps-v8.json
            'Link to JIRA ticket: https://jira.jira/jira/browse/${{ steps.parse-ticket-number.outputs.TICKET_NUMBER }}'