name: Terria catalog preview

on:
  push:
    branches:
      - terria_config_link
    paths:
      - '.github/workflows/terria_preview.yaml'
      - 'dev/terria/terria-cube-v8.json'
      - 'dev/terria/dea-maps-v8.json'

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:

      - name: Set branch name
        id: parse-branch-name
        run: |
            BRANCH_NAME=$(echo $GITHUB_REF | cut -d/ -f3)
            echo "::set-output name= BRANCH_NAME::$BRANCH_NAME"

      - uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            **Terria Cube config preview:** https://terria-cube.terria.io/#clean&https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/terria_config_link/dev/terria/terria-cube-v8.json
            
            **DEA Maps config preview:** https://maps.dea.ga.gov.au/#clean&https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/terria_config_link/dev/terria/dea-maps-v8.json
            
            Link to JIRA ticket: https://jira.jira/jira/browse/${{ steps.parse-branch-name.outputs.BRANCH_NAME }}