name: Terria catalog preview

on:
  push:
    branches:
      - terria_config_link
    paths:
      - '.github/workflows/terria_preview.yaml'
      - 'dev/terria/terria-cube-v8.json'
      - 'dev/terria/dea-maps-v8.json'

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:

      - name: Set branch name
        id: parse-branch-name
        run: |
            BRANCH_NAME=$(echo $GITHUB_REF | cut -d/ -f3)
            echo "Branch name is: $BRANCH_NAME"
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
      - uses: mshick/add-pr-comment@v2
        with:
          message: 'Branch name is: ${{ steps.parse-branch-name.outputs.BRANCH_NAME }}'