name : Terria catalog Linting

on:
  push:
    branches: [ master ]
    paths:
      - 'dev/terria/**'
      - .github/workflows/terria_linting.yaml
  pull_request:
    branches: [ master ]
    paths:
      - 'dev/terria/**'
      - .github/workflows/terria_linting.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Run Json Linter
      run: |
        npm install jsonlint -g
        jsonlint dev/terria/**.json -q
